### ISSUE TITLE
Rendering MP4 is not possible

### ISSUE THREAD

**Issue by svatas** [satishsampath/wink-issues#1] opened 2020-08-27 09:08 UTC
I just started with capturing the video. When I tried to render with settings 
![wink3-bug-render-01](https://user-images.githubusercontent.com/2070628/91420822-76219d00-e855-11ea-8ec5-6876fdb00790.png)

I got this error : 

![image](https://user-images.githubusercontent.com/2070628/91420890-89cd0380-e855-11ea-9115-2f62d87db506.png)

**Comment by satishsampath** [comment] 2020-08-28 05:00
Is this happening for the sample projects included with Wink as well (under the installed Wink\Samples folder) or only for the new captures you've made?

**Comment by satishsampath** [comment] 2020-08-28 05:23
Is it possible for you to attach the .wnk project that is giving you this error?

**Comment by svatas** [comment] 2020-08-28 08:27
Here you are.
[wink-beta.zip](https://github.com/satishsampath/wink-issues/files/5140943/wink-beta.zip)

This is just test project

**Comment by svatas** [comment] 2020-08-28 08:28
The strange thing is, that this is just for that special newly created project. I also tested a lot of more without any problem. The difference is, that I just used inserted message box and button. But I only guess.

**Comment by satishsampath** [comment] 2020-08-29 06:19
So.. the problem is that MP4 (or actually, the h264 video codec used by Wink for mp4) wants the video width & height to be a multiple of 2! This project has an odd number for width & height, hence the issue. If you "Project > Resize All Frames" to an even number width & height, it works fine.
I'll change the capture logic to always capture even sized frames in the next build.

**Comment by satishsampath** [comment] 2020-08-30 05:23
Posted in the beta group about latest build with fix, so closing.

**Closed by satishsampath** 2020-08-30 05:23 UTC
Labels: fixready
