### ISSUE TITLE
Slow rendered playback

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-issues#16] opened 2020-09-04 01:18 UTC
Both new and transferred Wink 2.0 winks playback in slow motion. I have not found a significant combination of capture and render frame rates to impact this behavior.

I am running Windows 10 Home edition 64 bit on an HP 15 laptop with 6 GB of RAM 

currently.

**Comment by satishsampath** [comment] 2020-09-04 01:20
When you say slow, are you referring to "rendering a project within Wink is slow" or "playing back the video in a browser is slow"?

**Comment by t-rains** [comment] 2020-09-04 02:25
It’s the playback in the browser that’s slow. Sorry for the ambiguity.

**Comment by satishsampath** [comment] 2020-09-04 03:54
Is there an MP4 video that you can attach here?

**Comment by vivonslasieste** [comment] 2020-09-04 08:40
It seems to me that I have the same problem but I didn't measure it accurately.

Maybe a solution would be to include in the bar the possibility to change the speed of the MP4 by 1.25, 1.5, 2.

This way, it is the final reader (for me the students) who decides whether they should pass the document faster or slower.

I say this but I confess that I don't know the complexity of adding this feature.

**Comment by satishsampath** [comment] 2020-09-05 06:50
@t-rains  @vivonslasieste  I wonder if the problem is because of a high value for "Frame rate" in the Project>Settings dialog. Please post here what value you see in your projects. Also, can you lower that value, say to 10 fps or something, and render?Please check if that makes the issue go away.

**Comment by vivonslasieste** [comment] 2020-09-05 13:51
You are right !

 

I had the problem with 20 frames/s

I set to 10 frames/s and all the buttons are visible and work.

 

I test this inside the “view render output” of wink.

I will test in firefox tomorrow (I have some family at home today).

 

But, I am optimist, if it works as well, for me, as I can decide to set to 10 frames, this bug is no longer a serious bug !

 

Thank’s again

 

 

De : Satish Sampath <notifications@github.com> 
Envoyé : samedi 5 septembre 2020 08:50
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] Slow rendered playback (#16)

 

@t-rains <https://github.com/t-rains>  @vivonslasieste <https://github.com/vivonslasieste>  I wonder if the problem is because of a high value for "Frame rate" in the Project>Settings dialog. Please post here what value you see in your projects. Also, can you lower that value, say to 10 fps or something, and render?Please check if that makes the issue go away.

**Comment by vivonslasieste** [comment] 2020-09-05 13:58
Sorry i made a mistake in my last comment :

Set to 10 frames does not resolve the slow rendered playback
But
it resolves the "mp4 viewing does not stop on the right frame" issue.

**Comment by t-rains** [comment] 2020-09-05 18:32
The Timed Capture Test 1 was done with the default 4 frames/second capture and 20 frames per second render.

The Timed Capture Test 3 was done with 1 frame/sec capture and 10 frames/sec render.

The Single Frame Capture Test 1 was done with manual screen snapshots capture and 20 frames/sec render.

**Comment by t-rains** [comment] 2020-09-05 18:36
I don't think the MP4 files downloaded here as I get a "We don't support that file type" message. Is there another way to pass these to you?

**Comment by satishsampath** [comment] 2020-09-05 21:20
You can upload the files to your personal Google Drive, share with my email ID and link here. Is that ok?
The other option is that you can just attach the .wnk files and I can render it myself

**Comment by satishsampath** [comment] 2020-09-07 07:24
@t-rains is this still an issue with the latest build (2.505)?

**Comment by vivonslasieste** [comment] 2020-09-07 07:53
I'm far from having tested everything, especially when creating new documents, but this version allows me to save all my old work and that's great news.

 

From my point of view, it lacks the possibility to move forward, stop or move backward by clicking directly on the mp3 scrollbar. Please let me know if you think you can add this feature by the end of the year.

Thanks again for your work.

 

De : Satish Sampath <notifications@github.com> 
Envoyé : lundi 7 septembre 2020 09:25
À : satishsampath/wink-issues <wink-issues@noreply.github.com>
Cc : vivonslasieste <vivonslasieste@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [satishsampath/wink-issues] Slow rendered playback (#16)

 

@t-rains <https://github.com/t-rains>  is this still an issue with the latest build (2.505)?

**Comment by t-rains** [comment] 2020-09-09 01:05
I have attempted to upload timed capture tests done on Build 2.506 to Google Drive and set you up as an editor. If that didn't work, please let me know.

**Comment by t-rains** [comment] 2020-09-09 01:21
I have attempted another method to link files to you in Google Drive. The link is 

https://drive.google.com/drive/folders/1q-naIlkh-woLP0RqL-1oq7AstbLds5nz?usp=sharing

**Comment by satishsampath** [comment] 2020-09-09 01:59
Is the issue not happening anymore in the latest build?

**Comment by t-rains** [comment] 2020-09-09 02:53
Yes. The behavior has not improved with the current Build.

**Comment by t-rains** [comment] 2020-09-09 02:54
Were you able to get the downloaded files?

**Comment by satishsampath** [comment] 2020-09-09 04:08
The drive link said I need to request access, so I have. Can you please check and grant me access?
I'm also confused a bit - you closed this github issue (which means the issue is fixed), but you said the behavior has not improved in the latest build. Which one is it? :) Should we reopen this issue if it is still happening?

**Comment by t-rains** [comment] 2020-09-09 04:33
I did not mean to close the issue, that was a mistake with my touchpad. 

I am sorry, I do not work with Google Drive. I do not see any place to grant access. Share+ only asks about adding contacts that I can see. 
![Google Drive Share+ Screen](https://user-images.githubusercontent.com/70729692/92554340-f4991a00-f219-11ea-988b-d4ec095ba29f.png)

**Comment by satishsampath** [comment] 2020-09-10 06:10
t-rains, can you please add my gmail ID to this google drive file? I had sent you an email from my gmail account.

**Comment by satishsampath** [comment] 2020-09-14 17:54
@t-rains Thanks for adding me to the drive folder. After looking at the videos, I think I understand the issue. 

Basically, you are using timed capture to take screenshots. Depending on what output frame rate you set, the output video can be either slow or fast. For example, the file "Timed Capture - 01f01r.wnk" shows a 1 frame/second capture and when rendered it shows each frame for 1 second as you would expect. But, the file "Timed Capture - 04f04r.wnk" was captured with almost 4 frames/second (sometimes 3, sometimes 5 etc).. and each frame actually shows up for 1 second in the output. Hence, the output video looks quite slow.

Is that correct? 

If yes, I think the fix is to also capture the time difference between each 'timed capture' frame so that it is set as the value for "Stay in this frame for ___ sec" for that frame. Then, when you render the video will show it for the correct amount of time.

**Comment by satishsampath** [comment] 2020-09-14 17:54
If you agree with my understanding above, I can make the fix in the next update.

**Comment by t-rains** [comment] 2020-09-14 18:27
Yes, I agree with that explanation of what is happening.

**Comment by satishsampath** [comment] 2020-09-15 05:34
Fix is ready and should be in the next beta release.

**Comment by t-rains** [comment] 2020-09-15 15:32
Great. I look forward to it.

**Comment by satishsampath** [comment] 2020-09-20 07:05
Fixed in release candidate build 2.508

**Closed by satishsampath** 2020-09-20 07:05 UTC
Labels: fixready
